### ISSUE TITLE
morning peer-to-peer

### ISSUE THREAD

**Issue by tingamapuro04** [AngomRanjan/AwesomeBooks#4]

**Comment by Bornittah** [comment]
**Good points to note**
- Professional README :heavy_check_mark:
- Clean code :heavy_check_mark:
- Good commit messages :heavy_check_mark:
- Good descriptive PR :heavy_check_mark:

**Comment by stephnna** [comment]
Your work is great, but the readme file still need improvement. One of the authors LinkedIn and Twitter account has not been connected. Connecting this will help others connect with you at social platforms
